name: nespresso

services:
  db:
    image: postgres:15
    container_name: nespresso_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 6
    networks:
      - nespresso_network
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgresql/data:/var/lib/postgresql/data

  opensearch:
    image: opensearchproject/opensearch:3.0.0
    container_name: nespresso_opensearch
    restart: always
    environment:
      - cluster.name=nespresso-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - plugins.security.disabled=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx2g"
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=${OPENSEARCH_INITIAL_ADMIN_PASSWORD}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:9200/_cluster/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 6
    networks:
      - nespresso_network
    ports:
      - "9200:9200"
      - "9600:9600"
    volumes:
      - ./data/recsys/opensearch/data:/usr/share/opensearch/data

  # opensearch-dashboards:
  #   image: opensearchproject/opensearch-dashboards:latest
  #   container_name: opensearch-dashboards
  #   ports:
  #     - "5601:5601"
  #   environment:
  #     OPENSEARCH_HOSTS: '["http://opensearch:9200"]'
  #   depends_on:
  #     - opensearch

  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nespresso_bot
    depends_on:
      db:
        condition: service_healthy
      opensearch:
        condition: service_healthy
    volumes:
      - ./data/logs/bot:/usr/src/app/data/logs/bot
      - ./data/recsys:/usr/src/app/data/recsys
    networks:
      - nespresso_network
    stdin_open: true              # Keeps STDIN open
    tty: true                     # Allocates a pseudo-TTY
    command: python -m nespresso

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nespresso_api
    depends_on:
      db:
        condition: service_healthy
      opensearch:
        condition: service_healthy
    volumes:
      - ./data/logs/api:/usr/src/app/data/logs/api
      - ./data/recsys:/usr/src/app/data/recsys
    ports:
      - "8000:8000"
    networks:
      - nespresso_network
    command: uvicorn nespresso.api.app:app --host 0.0.0.0 --port 8000 --app-dir src --reload --log-level info

networks:
  nespresso_network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
  opensearch_data:
    driver: local
