name: nespresso

services:
  db:
    image: postgres:15
    container_name: nespresso_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - nespresso_network
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgresql/data:/var/lib/postgresql/data

  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nespresso_bot
    volumes:
      - ./logs:/usr/src/app/logs
    networks:
      - nespresso_network
    stdin_open: true  # Keeps STDIN open
    tty: true         # Allocates a pseudo-TTY
    # command: python -m nespresso
    command: bash

networks:
  nespresso_network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
