from nespresso.recsys.searching.document import UpsertTextOpenSearch
from nespresso.recsys.searching.index import (
    DeleteOpenSearchIndex,
    DocSide,
    EnsureOpenSearchIndex,
)

user_texts = [
    "Hi, I’m Maria. I have a Bachelor’s degree in Computer Science and work as a data analyst at Insight Analytics. I love working with large datasets and using Python to find hidden patterns.",
    "Hello, I’m Daniel. I have a Master’s in Marketing and currently work at Bloom Agency as a marketing strategist. I have 4 years of experience in social media campaigns and SEO, and I’m always looking for new challenges.",
    "My name is Li, and I’m a software engineer at TechNova. I hold a degree in Software Engineering from Tsinghua University. My focus is on backend development and optimizing microservice architectures. I’ve previously worked with cloud solutions at ByteSystems and enjoy learning about new programming frameworks.",
    "Hello! I’m Michael, a UX/UI designer with 7 years of experience. I studied Graphic Design at the University of California, and now I work at Creative Labs, where I focus on making digital products more user-friendly. Before this, I spent 3 years at PixelStudio designing e-commerce platforms. I’m passionate about blending design and technology to create memorable user experiences.",
    "Hi! My name is Alice, and I’m a project manager at BuildPro, a construction technology startup. I have a degree in Civil Engineering from the University of Toronto and transitioned into project management after 5 years of field experience at Skyline Contractors. At BuildPro, I’m responsible for coordinating cross-functional teams and ensuring our software solutions meet clients’ needs. My expertise is in agile methodologies, and I’m always seeking ways to improve communication and efficiency across teams. I’m also part of a professional network for women in construction tech, where I mentor new project managers. I’m passionate about bridging the gap between traditional construction practices and digital innovation.",
    "I’m Lucas, a senior financial analyst at DeltaBank. I hold an MBA in Finance from the London School of Economics. Over the last 6 years, I’ve worked on financial planning and analysis projects, including M&A due diligence and capital market strategies. Before joining DeltaBank, I spent 4 years at FinTrust Group, where I focused on credit risk assessments for large enterprises. At DeltaBank, my role includes analyzing macroeconomic trends, advising on portfolio allocations, and developing predictive models using Python and R. I love collaborating with data engineers to create automated dashboards that help stakeholders make data-driven decisions. Outside of work, I’m a guest lecturer at the local business school, where I teach financial modeling to MBA students. I’m passionate about continuous learning and always looking to connect with fellow finance professionals.",
    "Hello, I’m Priya, a supply chain specialist currently working at GlobalGoods, a multinational logistics company. My educational background includes a Bachelor’s in Industrial Engineering from IIT Bombay and a Master’s in Supply Chain Management from MIT. In my early career at ShipSmart, I focused on optimizing last-mile delivery routes using advanced routing algorithms. At GlobalGoods, I manage end-to-end supply chain solutions for clients in the retail sector. My day-to-day work involves analyzing transportation data, collaborating with warehouse teams, and negotiating contracts with suppliers across Asia and Europe. I also lead sustainability initiatives, aiming to reduce carbon footprints in our logistics network. My technical skills include SQL, Tableau, and Python for data visualization. I’ve spoken at industry conferences about the future of green supply chains, and I enjoy sharing best practices on LinkedIn. My long-term goal is to help companies build more resilient and sustainable supply chains. Let’s connect if you’re interested in sustainable logistics or data-driven supply chain improvements!",
    "Hi! I’m Samira, and I’m a machine learning engineer at DataWave, a fast-growing AI startup. My journey began with a Bachelor’s in Electrical Engineering from Stanford, followed by a Master’s in AI from ETH Zurich. I started my career as a data scientist at TechSolutions, working on predictive maintenance models for manufacturing companies. After that, I moved to FinTech Labs, where I developed credit scoring models using gradient boosting and deep learning techniques. At DataWave, I focus on building scalable recommendation systems and NLP-based search solutions for e-commerce clients. My role involves close collaboration with product managers to ensure our AI models are production-ready and deliver business value. I’m proficient in Python, TensorFlow, and Spark, and I’m always experimenting with new architectures like transformers for text data. I also mentor junior engineers in our team, helping them develop their coding and research skills. Outside of work, I contribute to open-source projects and recently published a paper on improving transformer-based embeddings in financial forecasting. I’m particularly interested in ethical AI and how to make machine learning models fairer and more transparent. If you’d like to chat about deep learning applications in e-commerce or share ideas for collaborative research, feel free to reach out—I’m always happy to connect!",
    "Hi, I’m Tom. I’m the CTO at InnovateX, where I lead teams in building scalable SaaS solutions. My background is in computer science and cloud infrastructure, and I previously worked at CloudWave.",
    "I’m Elena, a product manager with a passion for turning ideas into reality. My education in design and business at HEC Paris taught me to see beyond the obvious and challenge the status quo. Currently at UrbanTech, I’m leading cross-functional teams to launch products that improve urban mobility. Before that, I was at MobilityOne, where I crafted solutions that connected cities. I’m driven by a belief that technology should serve people and the planet. My next chapter? I hope to work on projects that blend sustainability, innovation, and human-centered design. Let’s make cities smarter, one product at a time."
    "Hi, I’m Nadia, an HR business partner at PeopleFirst. My degree is in Organizational Psychology from the University of Amsterdam, and I have 7 years of experience working with fast-growing startups. At PeopleFirst, I design employee engagement programs and lead diversity initiatives to foster inclusive cultures. Before this, I was an HR consultant at TalentWorks, where I specialized in leadership development workshops for tech companies. My mission is to help organizations become more people-centric and resilient.",
    "I’m Ethan, a renewable energy consultant at SunTech Solutions. My background is in Environmental Engineering, and I hold a Master’s from TU Munich. Over the last 5 years, I’ve worked with utility-scale solar and wind projects, managing feasibility studies and environmental impact assessments. I’m currently focused on helping mid-size companies transition to renewable energy sources and optimize their energy portfolios. Outside of work, I’m an advocate for community solar initiatives and regularly speak at clean energy conferences.",
    "Hi, I’m Misha, a data privacy officer at SecureComply. With a law degree from UCL and a CIPP/E certification, I specialize in GDPR compliance and data governance. At SecureComply, I conduct data protection impact assessments and train teams on privacy-by-design practices. Before this, I was a privacy consultant at DataRights, where I worked with SaaS startups and financial institutions. My goal is to make data privacy not just a checkbox, but a competitive advantage for businesses.",
    "I’m Leo, a frontend engineer at FlowForge, where I build performant and accessible web applications. My background is in Computer Science from UCSD, and I have 4 years of experience with React and TypeScript. At FlowForge, I collaborate with designers to create intuitive UIs and lead efforts to improve our web performance scores. I’m also active in the open-source community, contributing to React libraries and sharing tips for accessible design.",
    "Hello, I’m Gabriela, a business analyst at SmartCommerce. I hold a Master’s in Business Analytics from ESSEC Business School and specialize in customer journey optimization for retail clients. My job involves analyzing large datasets to identify purchasing patterns and creating actionable insights for marketing and product teams. Previously, I worked at RetailNext, where I built predictive models for in-store conversion rates. I’m passionate about using data to create seamless shopping experiences.",
    "I’m Jonas, a mechanical design engineer at AeroMach. I have a Bachelor’s in Mechanical Engineering from KTH Royal Institute of Technology, and I focus on designing lightweight aerospace components. At AeroMach, I work on CAD modeling, stress analysis, and prototype testing for next-generation aircraft. Before this, I was part of a Formula Student team, where I led the chassis design. I’m always seeking new challenges in sustainable aviation and love tinkering with drones in my spare time.",
    "Hi! I’m Aria, a customer success manager at SaaSify, a startup that helps businesses streamline their workflows. My background is in Business Administration from the University of Melbourne. I started in technical support at HelpDesk Pro and quickly moved into customer onboarding and retention. At SaaSify, I build relationships with clients to ensure they achieve their goals and get the most out of our platform. I’m also a certified Scrum Master and enjoy helping cross-functional teams work better together.",
    "I’m Victor, a data engineer at DataPipe, where I design ETL pipelines and optimize data warehouse performance. I studied Computer Engineering at Warsaw University of Technology and have worked with distributed systems for the last 5 years. My experience includes building real-time data processing architectures with Kafka and Spark. Before DataPipe, I worked at CloudData, where I focused on implementing data governance frameworks. I love solving data challenges and sharing best practices with the community.",
    "Hi, I’m Chloe, a digital product designer at HorizonApps. I have a degree in Interaction Design from the University of Sydney and a passion for creating user-centered products. At HorizonApps, I design intuitive interfaces for mobile and web apps, collaborating with product managers and engineers to bring ideas to life. Before this, I was a UX researcher at ClickLab, where I conducted usability studies and user interviews to inform design decisions. I’m driven by curiosity and a love for clean, elegant design.",
    "I’m Peter, a DevOps engineer at CloudScale. My background is in Electrical Engineering from the University of Texas, and I’ve been working with cloud infrastructure and CI/CD pipelines for 6 years. At CloudScale, I automate deployments, monitor system health, and ensure high availability for mission-critical applications. My stack includes Terraform, Kubernetes, and Prometheus, and I’m always experimenting with new tools to make our workflows more efficient. Outside of work, I mentor junior engineers and contribute to open-source DevOps projects.",
    "I’m Alex, a cybersecurity consultant at CyberTrust Solutions. With a Bachelor’s degree in Information Security from NYU, I help companies safeguard their digital assets. My work involves performing security audits, developing incident response plans, and training employees on best practices. Before joining CyberTrust, I was a security analyst at ShieldTech, focusing on intrusion detection systems. My passion is combining technical skills with human factors to create robust security postures. I’m also active in the cybersecurity community, speaking at DEF CON and contributing to open-source tools for threat hunting. Let’s connect if you want to discuss cloud security or zero-trust architectures!",
    "Hi, I’m Emily, a sustainability consultant at GreenWay Partners. My background is in Environmental Science, with a Master’s from the University of British Columbia. Over the past 5 years, I’ve helped companies in the manufacturing and retail sectors reduce their carbon footprints and transition to renewable energy sources. At GreenWay, I’m responsible for conducting life cycle assessments and developing ESG strategies for clients across North America. Previously, I worked at EcoLogica, where I implemented circular economy practices for apparel brands. My work blends data analysis with stakeholder engagement to make sustainability actionable and profitable.",
    "I’m Jason, a mechanical engineer at AeroDynamics Inc., specializing in lightweight materials for aerospace applications. With a degree from Georgia Tech, I design components that improve fuel efficiency and reduce environmental impact. My work has included leading finite element analysis for new wing designs and collaborating with suppliers to ensure high-precision manufacturing. Before AeroDynamics, I spent 2 years at MetalForm, working on structural components for automotive systems. Outside of work, I volunteer at engineering outreach programs to inspire the next generation of innovators.",
    "Hello, I’m Sofia, a data product manager at DataFusion. My background is in statistics and data engineering, with a degree from TU Delft. I’ve spent the past 6 years bridging the gap between data teams and business units. At DataFusion, I define product roadmaps for our analytics platform and work closely with ML engineers to ensure data integrity. Before this, I was a data analyst at InsightWorks, where I built dashboards to track product KPIs and experimented with A/B testing frameworks. I’m passionate about data democratization and fostering a data-driven culture in every organization I work with.",
    "I’m Carlos, a cloud solutions architect at SkyNetix, where I design scalable cloud infrastructure for enterprise clients. My expertise includes AWS, Azure, and Kubernetes, and I have a Master’s in Computer Science from the University of São Paulo. I started my career as a software developer at DevCore, where I learned the importance of reliable CI/CD pipelines. At SkyNetix, I lead cloud migration projects and advise clients on cloud-native architectures. Outside of work, I’m active in local tech meetups and contribute to open-source DevOps tools.",
    "Hi, I’m Rachel, a content strategist at DigitalBridge. I have a Bachelor’s in Communications and 5 years of experience crafting compelling digital narratives. At DigitalBridge, I lead content marketing campaigns for B2B SaaS clients, ensuring that our messaging resonates with target audiences. Previously, I worked at MediaSpark as a copywriter, helping startups tell their stories through blog posts, case studies, and social media. My passion lies in blending data-driven insights with creative storytelling to build authentic brand voices.",
    "I’m Omar, a robotics engineer at RoboMinds. I earned my Master’s in Mechatronics from ETH Zurich and specialize in autonomous navigation systems for industrial robots. My day-to-day involves developing SLAM algorithms, integrating hardware components, and testing prototypes in our labs. Previously, I worked at AutoBotics, where I focused on path planning for delivery drones. I’m passionate about the intersection of AI and robotics and actively participate in ROS (Robot Operating System) communities to share my learnings.",
    "Hi! I’m Julia, a digital marketing specialist at PixelGrowth. My background is in Business Administration from HEC Montreal, and I’ve spent the last 4 years driving growth for e-commerce brands through paid media and conversion optimization. At PixelGrowth, I manage campaigns across Meta Ads, Google Ads, and TikTok, leveraging data to refine audience targeting and messaging. I’m also certified in Google Analytics and love turning insights into revenue-driving strategies. Let’s chat if you’re looking to boost your digital presence!",
    "I’m Anya, a biomedical researcher at MedTech Labs. With a PhD in Molecular Biology from the University of Cambridge, my work focuses on developing diagnostic tools for infectious diseases. I’ve authored several peer-reviewed articles and presented at international medical conferences. At MedTech Labs, I lead a team of researchers exploring CRISPR-based diagnostics for early detection of viral infections. Collaboration and innovation are at the core of my work, and I’m always eager to discuss new ideas with fellow scientists.",
    "Hello, I’m Mark, a supply chain analyst at FreshLogistics, where I focus on optimizing cold chain logistics for food distribution. My degree is in Industrial Engineering from Purdue University, and I started my career at FreightFirst as an operations planner. At FreshLogistics, I work with data engineers to create predictive models for demand forecasting and route optimization. I’m particularly interested in using AI to improve food safety and reduce waste in the supply chain. Let’s connect if you want to chat about the future of cold chain logistics or data-driven optimization in transportation.",
]


async def DoShit() -> None:
    await EnsureOpenSearchIndex()
    await DeleteOpenSearchIndex()
    await EnsureOpenSearchIndex()

    for nes_id, text in enumerate(user_texts):
        await UpsertTextOpenSearch(nes_id=nes_id, side=DocSide.cv, text=text)
